name: Davidwang
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49654
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfe3ef'
    - '#0a070e'
    - '#b6bad3'
    - '#48495b'
    - '#00669d'
  brandStrength: 0
  lightness: 0.9375
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
